export type DraftCardSeed = {
  slug: string;
  title: string;
  collection: string[];
  primaryType: "TACTIC" | "FACT" | "THEOLOGY" | "CASE" | "REFERENCE";
  status: "ESTABLISHED" | "CONTESTED" | "OPEN" | "CONTEXT_DEPENDENT" | "UNSUPPORTED" | "LIVE";
  axis: string[];
  mechanisms?: string[];
  summary?: string;
  editorialNotes?: string;
};

export const draftCards: DraftCardSeed[] = [

  { slug: "jesus-is-a-muslim", title: "Jesus Is a Muslim", collection: ["zionism-coded"], primaryType: "THEOLOGY", status: "CONTESTED", axis: ["THEOLOGICAL", "FACT-REBUTTAL"], mechanisms: ["anachronism", "retrospective-identity"], summary: "Examines the Islamic theological description of Jesus as a prophet and the retrospective use of the category Muslim for a first-century figure.", editorialNotes: "Separate Qur’anic theological usage from modern confessional, national, and political identity categories. Do not collapse Jesus-as-Muslim into Jesus-as-Palestinian." },
  { slug: "jesus-was-a-palestinian", title: "Jesus Was a Palestinian", collection: ["fact-rebuttal"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["anachronism", "retrospective-identity"], summary: "Examines the retrospective application of the modern Palestinian national/geographical identity to the historical Jesus, Mary, and Joseph.", editorialNotes: "Distinguish first-century geography, Roman provincial terminology, later uses of Palestine, and modern Palestinian national identity." },
  { slug: "muhammad-was-a-zionist", title: "Muhammad Was a Zionist", collection: ["zionism-coded"], primaryType: "THEOLOGY", status: "CONTESTED", axis: ["THEOLOGICAL", "FACT-REBUTTAL"], mechanisms: ["anachronism", "retrospective-identity"], summary: "Tests the proposition that Qur’anic references to the Children of Israel and the land establish that Muhammad held the modern political ideology of Zionism.", editorialNotes: "Keep Qur’anic land references as independent source material. Do not treat recognition of a Jewish connection to the land as evidence by itself of modern Zionist political ideology." },
  { slug: "land-of-the-children-of-israel", title: "The Land of the Children of Israel", collection: ["fact-rebuttal"], primaryType: "REFERENCE", status: "CONTESTED", axis: ["THEOLOGICAL", "FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "Primary-source reference card for Qur’anic passages concerning the Children of Israel and the land, separated from later political interpretations.", editorialNotes: "Attach the relevant Qur’anic passages as primary sources with translation/version metadata. The source card should not itself infer modern territorial sovereignty or Zionist ideology." },
  { slug: "shylock", title: "Shylock", collection: ["classic"], primaryType: "TACTIC", status: "ESTABLISHED", axis: ["TACTIC"], mechanisms: ["essentialisation"], summary: "A historical stereotype associating Jews with deceptive commerce, predatory lending, or usury.", editorialNotes: "Retain the circularity mechanism while distinguishing regions and periods." },
  { slug: "mossad-agent", title: "Mossad Agent", collection: ["classic"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["conspiracy", "collectivisation"], summary: "An accusation that a person is a covert Israeli intelligence operative without evidence beyond identity, affiliation, or political position." },
  { slug: "zio-nazi", title: "Zio Nazi", collection: ["classic"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["inversion", "equivalence"], summary: "A Nazi/Israel or Nazi/Zionism equivalence that can become Holocaust inversion when persecuted and persecutor roles are rhetorically reversed." },
  { slug: "world-domination", title: "World Domination", collection: ["classic"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["conspiracy"], summary: "Claims that Jews or Zionists secretly control major institutions as part of a coordinated hidden agenda." },
  { slug: "dual-loyalty", title: "Dual Loyalty", collection: ["classic"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["collectivisation", "essentialisation"], summary: "Treating Jewish identity or connection to Israel as evidence that a person cannot be a fully loyal citizen." },
  { slug: "blood-libel", title: "Blood Libel", collection: ["classic"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["demonisation", "substitution"], summary: "The historical child-murder accusation and its possible structural mutation into collective claims about Jews or Zionists." },
  { slug: "holocaust-denial-distortion", title: "Holocaust Denial / Distortion", collection: ["classic"], primaryType: "FACT", status: "ESTABLISHED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping", "inversion"], summary: "Distinguishes denial of the Nazi genocide of European Jews from minimisation, chronology manipulation, selective comparison, or inversion." },
  { slug: "talmud", title: "Talmud", collection: ["classic"], primaryType: "THEOLOGY", status: "CONTEXT_DEPENDENT", axis: ["TACTIC", "THEOLOGICAL"], mechanisms: ["context-stripping"], summary: "Challenges treating the Talmud as a single binding operational manual while quoting isolated passages without context." },
  { slug: "chosen-people-master-race", title: "Chosen People / Master Race", collection: ["classic"], primaryType: "THEOLOGY", status: "CONTESTED", axis: ["TACTIC", "THEOLOGICAL"], mechanisms: ["equivalence", "essentialisation"], summary: "Examines the translation of the Jewish theological concept of chosenness into a racial-supremacy category." },
  { slug: "haavara-blood-for-goods", title: "Haavara / Blood for Goods", collection: ["classic"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["inversion", "context-stripping"], summary: "Examines the Haavara Agreement and related rescue controversies without collapsing distinct episodes into one claim." },
  { slug: "elders-of-zion", title: "Elders of Zion", collection: ["classic"], primaryType: "FACT", status: "ESTABLISHED", axis: ["FACT-REBUTTAL", "TACTIC"], mechanisms: ["conspiracy"], summary: "The Protocols of the Elders of Zion as a fabricated conspiracy text and influential antisemitic forgery." },
  { slug: "jews-are-not-white", title: "Jews Are Not White", collection: ["classic"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["racial-essentialism"], summary: "Examines categorical racial classification of diverse Jewish populations." },
  { slug: "goy", title: "Goy", collection: ["zionism-coded"], primaryType: "THEOLOGY", status: "CONTEXT_DEPENDENT", axis: ["THEOLOGICAL"], mechanisms: ["context-stripping"], summary: "Examines the Hebrew term goy and the difference between biblical and later usage." },
  { slug: "replacement-theology", title: "Replacement Theology", collection: ["zionism-coded"], primaryType: "THEOLOGY", status: "CONTESTED", axis: ["THEOLOGICAL"], mechanisms: ["equivalence"], summary: "Examines Christian supersessionist or replacement-theology positions and their political implications without equating theological disagreement with antisemitism." },
  { slug: "apartheid-collaborators", title: "Apartheid Collaborators", collection: ["zionism-coded"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["equivalence", "context-stripping"], summary: "A comparative history question concerning Israel's relationship with apartheid South Africa and claims of unique responsibility." },
  { slug: "white-european-settlers", title: "White, European Settlers", collection: ["zionism-coded"], primaryType: "FACT", status: "CONTEXT_DEPENDENT", axis: ["FACT-REBUTTAL"], mechanisms: ["racial-essentialism"], summary: "Examines claims that Israeli Jews can be categorised simply as white European settlers." },
  { slug: "settler-colonialism", title: "Settler-Colonialism", collection: ["zionism-coded"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["essentialisation", "equivalence"], summary: "Treats settler-colonialism as an analytical framework whose explanatory scope and omissions should be examined rather than treated as a complete historical verdict." },
  { slug: "zionist-as-slur", title: "Zionist-as-Slur", collection: ["zionism-coded"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["substitution", "collectivisation"], summary: "Examines when a political label is used as a proxy for a Jewish or ethnic group." },
  { slug: "litmus-test-deplatforming", title: "Litmus Test / Deplatforming", collection: ["zionism-coded"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["exclusion", "guilt-by-association"], summary: "Examines exclusion based on assumed political affiliation rather than actual conduct or argument." },
  { slug: "platform-institutional-control", title: "Platform / Institutional Control", collection: ["zionism-coded"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["conspiracy"], summary: "Examines claims of hidden Jewish or Zionist control over institutions versus documented influence by identifiable actors." },
  { slug: "river-to-sea", title: "River to Sea", collection: ["zionism-coded"], primaryType: "THEOLOGY", status: "CONTEXT_DEPENDENT", axis: ["THEOLOGICAL"], mechanisms: ["context-stripping"], summary: "A context-dependent slogan with multiple documented interpretations." },
  { slug: "weaponizing-antisemitism", title: "Weaponizing Antisemitism", collection: ["zionism-coded"], primaryType: "TACTIC", status: "CONTESTED", axis: ["TACTIC"], mechanisms: ["inversion"], summary: "Examines claims that antisemitism allegations are used strategically to silence criticism, while allowing that the allegation itself can be overgeneralised." },
  { slug: "jews-are-white", title: "Jews Are White", collection: ["zionism-coded"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["racial-essentialism"], summary: "Examines categorical assignment of all Jews to a single white racial identity." },
  { slug: "jews-are-not-semites", title: "Jews Are Not Semites", collection: ["zionism-coded"], primaryType: "REFERENCE", status: "ESTABLISHED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "Explains the nineteenth-century political coinage of antisemitism and the distinction between linguistic Semitic classification and the modern term." },
  { slug: "cape-union-mart", title: "Cape Union Mart", collection: ["south-africa"], primaryType: "CASE", status: "LIVE", axis: ["FACT-REBUTTAL"], summary: "South African legal case concerning protest claims and alleged association with Israel, genocide, or military conflict." },
  { slug: "uct-resolutions", title: "UCT Resolutions", collection: ["south-africa"], primaryType: "CASE", status: "LIVE", axis: ["TACTIC", "FACT-REBUTTAL"], summary: "Institutional governance and boycott/IHRA-related resolutions at UCT." },
  { slug: "sa-jews-for-a-free-palestine", title: "SA Jews for a Free Palestine", collection: ["south-africa"], primaryType: "CASE", status: "CONTESTED", axis: ["TACTIC"], summary: "A regional case concerning arguments from Jewish identity and disagreement over political positions." },
  { slug: "mendelsohn", title: "Mendelsohn", collection: ["south-africa"], primaryType: "CASE", status: "LIVE", axis: ["FACT-REBUTTAL"], summary: "Case-study hub for the UCT Mendelsohn dispute, its pleadings, institutional context, and procedural history." },
  { slug: "jerusalem-sovereignty", title: "Jerusalem Sovereignty", collection: ["fact-rebuttal"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "Separates historical administration, present control, sovereignty claims, and international legal status." },
  { slug: "quran-land-claim", title: "Quran / Land Claim", collection: ["fact-rebuttal"], primaryType: "THEOLOGY", status: "CONTESTED", axis: ["THEOLOGICAL"], mechanisms: ["context-stripping"], summary: "Distinguishes scriptural descriptions from modern claims of exclusive territorial sovereignty." },
  { slug: "apartheid-map", title: "The Apartheid Map", collection: ["fact-rebuttal"], primaryType: "REFERENCE", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "Tests map sequences against the legal and political category represented by each map." },
  { slug: "voting-rights", title: "Voting Rights", collection: ["fact-rebuttal"], primaryType: "FACT", status: "ESTABLISHED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "Separates Israeli citizenship and national elections from the status of residents of the West Bank and Gaza." },
  { slug: "nakba-symmetry", title: "Nakba Symmetry", collection: ["fact-rebuttal"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["equivalence"], summary: "Compares Palestinian displacement in 1947–49 with Jewish displacement and migration from Arab and Muslim-majority countries." },
  { slug: "balfour-colonial-origins", title: "Balfour / Colonial Origins", collection: ["fact-rebuttal"], primaryType: "REFERENCE", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "A chronology of diplomatic and colonial documents surrounding the origins of the Mandate-era settlement." },
  { slug: "palestinian-flag", title: "Palestinian Flag", collection: ["fact-rebuttal"], primaryType: "REFERENCE", status: "ESTABLISHED", axis: ["FACT-REBUTTAL"], summary: "Distinguishes the Pan-Arab genealogy of the flag design from its later Palestinian national meaning." },
  { slug: "chronology", title: "Chronology", collection: ["fact-rebuttal"], primaryType: "REFERENCE", status: "ESTABLISHED", axis: ["FACT-REBUTTAL"], mechanisms: ["context-stripping"], summary: "Places competing national movements and political developments on their respective timelines." },
  { slug: "anc-hamas-equivalence", title: "ANC / Hamas Equivalence", collection: ["fact-rebuttal"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], mechanisms: ["equivalence", "context-stripping"], summary: "Separates the ANC's historical relationships and statements from later relationships between South African actors and Hamas." },
  { slug: "israel-apartheid-severance", title: "Israel–Apartheid Severance", collection: ["fact-rebuttal"], primaryType: "FACT", status: "ESTABLISHED", axis: ["FACT-REBUTTAL"], summary: "Examines the change over time in Israel's relationship with apartheid South Africa, including the 1987 severance of remaining military ties." },
  { slug: "false-binary-choose-sides", title: "False Binary / Choose Sides", collection: ["fact-rebuttal"], primaryType: "TACTIC", status: "CONTEXT_DEPENDENT", axis: ["TACTIC"], mechanisms: ["exclusion", "equivalence"], summary: "Examines demands to choose a collective side when the particular factual or legal question may require qualification." },
  { slug: "depo-provera", title: "Depo-Provera", collection: ["fact-rebuttal"], primaryType: "FACT", status: "CONTESTED", axis: ["FACT-REBUTTAL"], summary: "Separates documented medical-ethics issues, allegations of coercion, claims about state intent, and claims of a genocidal programme." },
  { slug: "ihra-vs-jerusalem-declaration", title: "IHRA vs Jerusalem Declaration", collection: ["fact-rebuttal"], primaryType: "REFERENCE", status: "CONTESTED", axis: ["FACT-REBUTTAL"], summary: "A documented dispute over definitions, scope, examples, and institutional use of competing antisemitism frameworks.", editorialNotes: "Renamed from the draft's categorical 'IHRA Isn't Valid'." },
];
