export const evidenceLayerExamples = {
  evidenceTypes: [
    "QUOTATION","PARAPHRASE","DATA_POINT","DOCUMENT_FEATURE",
    "IMAGE_FEATURE","TESTIMONY","SECONDARY_ASSESSMENT"
  ],
  relations: [
    "SUPPORTS","CHALLENGES","QUALIFIES","CONTEXTUALISES",
    "ILLUSTRATES","REPORTS","ATTRIBUTES"
  ],
  strengths: ["DIRECT","RELEVANT","INDIRECT","AMBIGUOUS","CONTESTED","UNSPECIFIED"],
  locatorTypes: [
    "PAGE","PARAGRAPH","SECTION","CHAPTER","VERSE","TIMESTAMP",
    "FIGURE","TABLE","URL_FRAGMENT","ARCHIVE_ID","SOURCE_SPECIFIC"
  ]
};
